name: "publish-windows-arm"

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "windows-latest"
            target: "aarch64-pc-windows-msvc"
            args: "--target aarch64-pc-windows-msvc"

    runs-on: ${{ matrix.platform }}
    # Add environment variables here

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-pc-windows-msvc

      - name: Install Windows ARM64 target
        run: rustup target add aarch64-pc-windows-msvc

      - name: Install ImageMagick
        run: choco install imagemagick.app -y

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v0.1.0
          releaseName: "App v0.1.0"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
          distPath: ./build
          bundleIdentifier: com.supabasecommunity.supabassomatic
          appName: "supa-bass-o-matic"
          appVersion: "0.1.0"
